### ISSUE TITLE
Error while inferencing

### ISSUE THREAD

**Issue by shiju80** [icml-2020-nlp/semsim#4]
Hi,
When I the run inference sample provided in the repo, I get the error while loading the model at this line -

bart = BARTModel.from_pretrained(
    'checkpoints/',
    checkpoint_file='semsim.pt',
    data_name_or_path='cnn_dm-bin'
)
How do I get the contents of cnn_dm-bin?
The error is - 
**KeyError: 'semantic_similarity_loss'**

Please Help

**Comment by icml-2020-nlp** [comment]
Hi, 
Thank you for your interest!
I cannot assure where the problem comes from, but it seems like your fairseq library is a normal version. (I would like to request more details about your situation.)

Have you installed fairseq from our source code (=modified fairseq)? 
You need to follow steps from [here](https://github.com/icml-2020-nlp/semsim#for-fine-tuning-and-inferencing-). Especially :
```
git clone https://github.com/icml-2020-nlp/semsim.git

cd fairseq-semsim
pip install --editable .
```
Thank you very much and I would like to hear from you about the matter. 
Best regards,

**Comment by shiju80** [comment]
Thanks a lot. That helped. Able to run test summaries.
